### ISSUE TITLE
Errors on start

### ISSUE THREAD

**Issue by mbierman** [paolotremadio/homebridge-automation-calendar#12]
After the newest release was installed and I restarted I see the following: 

	[6/27/2020, 4:12:03 AM] Error loading accessory requested in your config.json at position 7
	[6/27/2020, 4:12:03 AM] Error: The requested accessory 'AutomationCalendar' was not registered by any plugin.
	    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
	    at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
	    at Array.forEach (<anonymous>)
	    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
	    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
	    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
	    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
	    at Module._compile (internal/modules/cjs/loader.js:1138:30)
	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
	    at Module.load (internal/modules/cjs/loader.js:986:32)

**Comment by paolotremadio** [comment]
I cannot reproduce. How have you updated the plugin? please try to remove and re-add again.

**Comment by mbierman** [comment]
Confirmed that it still doesn't work for me. With the Previous version things are good. With the latest version... and it prevents homebridge from loading 

	[6/29/2020, 12:28:05 PM] ====================
	[6/29/2020, 12:28:05 PM] ERROR LOADING PLUGIN homebridge-automation-calendar:
	[6/29/2020, 12:28:05 PM] Error: Cannot find module 'hap-nodejs'
	Require stack:
	- /homebridge/node_modules/homebridge-automation-calendar/custom-characteristics.js
	- /homebridge/node_modules/homebridge-automation-calendar/index.js
	- /usr/local/lib/node_modules/homebridge/lib/plugin.js
	- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
	- /usr/local/lib/node_modules/homebridge/lib/api.js
	- /usr/local/lib/node_modules/homebridge/lib/server.js
	- /usr/local/lib/node_modules/homebridge/lib/cli.js
	- /usr/local/lib/node_modules/homebridge/bin/homebridge
	    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
	    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
	    at Module.require (internal/modules/cjs/loader.js:1026:19)
	    at require (internal/modules/cjs/helpers.js:72:18)
	    at Object.<anonymous> (/homebridge/node_modules/homebridge-automation-calendar/custom-characteristics.js:2:28)
	    at Module._compile (internal/modules/cjs/loader.js:1138:30)
	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
	    at Module.load (internal/modules/cjs/loader.js:986:32)
	    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
	    at Module.require (internal/modules/cjs/loader.js:1026:19)
	[6/29/2020, 12:28:05 PM] ====================

**Comment by paolotremadio** [comment]
Have you tested your PR? Because it works on my setup.

**Comment by paolotremadio** [comment]
I've released a further update. I still can't reproduce. Please investigate on your setup and re-open the issue if you have updates

**Comment by mbierman** [comment]
I'm not seeing these errors anymore with the latest release. Thank you!
